package config

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Config is the v1 public contract for a harness run.
type Config struct {
	Version       string   `json:"version"`
	RepoURL       string   `json:"repo_url"`
	Repo          string   `json:"repo"`
	BaseBranch    string   `json:"base_branch"`
	TargetSubdir  string   `json:"target_subdir"`
	Prompt        string   `json:"prompt"`
	CommitMessage string   `json:"commit_message"`
	PRTitle       string   `json:"pr_title"`
	PRBody        string   `json:"pr_body"`
	Labels        []string `json:"labels"`
	Reviewers     []string `json:"reviewers"`
}

// Load reads and validates a JSON/JSONC config from disk.
func Load(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("read config: %w", err)
	}

	cleaned := stripLineComments(data)
	var cfg Config
	dec := json.NewDecoder(bytes.NewReader(cleaned))
	if err := dec.Decode(&cfg); err != nil {
		return Config{}, fmt.Errorf("parse config json: %w", err)
	}

	cfg.ApplyDefaults()
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

// ApplyDefaults normalizes aliases and fills optional values.
func (c *Config) ApplyDefaults() {
	c.Version = strings.TrimSpace(c.Version)
	if c.Version == "" {
		c.Version = "v1"
	}

	if strings.TrimSpace(c.RepoURL) == "" && strings.TrimSpace(c.Repo) != "" {
		c.RepoURL = strings.TrimSpace(c.Repo)
	}

	c.BaseBranch = strings.TrimSpace(c.BaseBranch)
	if c.BaseBranch == "" {
		c.BaseBranch = "main"
	}

	c.TargetSubdir = strings.TrimSpace(c.TargetSubdir)
	if c.TargetSubdir == "" {
		c.TargetSubdir = "."
	}

	c.Prompt = strings.TrimSpace(c.Prompt)

	if strings.TrimSpace(c.CommitMessage) == "" {
		c.CommitMessage = defaultCommitMessage(c.Prompt)
	}
	if strings.TrimSpace(c.PRTitle) == "" {
		c.PRTitle = defaultPRTitle(c.Prompt)
	}
	if strings.TrimSpace(c.PRBody) == "" {
		c.PRBody = defaultPRBody(c.Prompt)
	}
}

// Validate checks required values and path safety.
func (c Config) Validate() error {
	if strings.TrimSpace(c.Version) == "" {
		return fmt.Errorf("version is required")
	}
	if c.Version != "v1" {
		return fmt.Errorf("unsupported version %q", c.Version)
	}
	if strings.TrimSpace(c.RepoURL) == "" {
		return fmt.Errorf("repo_url (or repo) is required")
	}
	if strings.TrimSpace(c.BaseBranch) == "" {
		return fmt.Errorf("base_branch is required")
	}
	if strings.TrimSpace(c.TargetSubdir) == "" {
		return fmt.Errorf("target_subdir is required")
	}
	if err := validateSubdir(c.TargetSubdir); err != nil {
		return err
	}
	if strings.TrimSpace(c.Prompt) == "" {
		return fmt.Errorf("prompt is required")
	}
	if strings.TrimSpace(c.CommitMessage) == "" {
		return fmt.Errorf("commit_message is required")
	}
	if strings.TrimSpace(c.PRTitle) == "" {
		return fmt.Errorf("pr_title is required")
	}
	if strings.TrimSpace(c.PRBody) == "" {
		return fmt.Errorf("pr_body is required")
	}
	return nil
}

func validateSubdir(subdir string) error {
	clean := filepath.Clean(subdir)
	if clean == "" {
		return fmt.Errorf("target_subdir must be a relative path")
	}
	if filepath.IsAbs(clean) {
		return fmt.Errorf("target_subdir must be relative")
	}
	if strings.HasPrefix(clean, "..") {
		return fmt.Errorf("target_subdir cannot escape repository root")
	}
	if strings.Contains(clean, ".."+string(filepath.Separator)) {
		return fmt.Errorf("target_subdir cannot contain parent traversals")
	}
	return nil
}

func defaultCommitMessage(prompt string) string {
	summary := summarize(prompt, 64)
	if summary == "" {
		return "chore: codex automated update"
	}
	return "chore: " + summary
}

func defaultPRTitle(prompt string) string {
	summary := summarize(prompt, 72)
	if summary == "" {
		return "Codex automated update"
	}
	return summary
}

func defaultPRBody(prompt string) string {
	summary := summarize(prompt, 500)
	if summary == "" {
		return "Automated change generated by codex harness."
	}
	return "Automated change generated by codex harness.\n\nPrompt:\n" + summary
}

var wsRE = regexp.MustCompile(`\s+`)

func summarize(s string, max int) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	s = wsRE.ReplaceAllString(s, " ")
	if len(s) <= max {
		return strings.Trim(s, ",.;:-")
	}

	s = s[:max]
	if i := strings.LastIndexByte(s, ' '); i > 0 {
		s = s[:i]
	}
	s = strings.TrimSpace(s)
	s = strings.Trim(s, ",.;:-")
	return s
}

func stripLineComments(data []byte) []byte {
	var out []byte
	inString := false
	escaped := false

	for i := 0; i < len(data); i++ {
		ch := data[i]

		if inString {
			out = append(out, ch)
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == '"' {
				inString = false
			}
			continue
		}

		if ch == '"' {
			inString = true
			out = append(out, ch)
			continue
		}

		// Drop JSONC-style single-line comments.
		if ch == '/' && i+1 < len(data) && data[i+1] == '/' {
			for i < len(data) && data[i] != '\n' {
				i++
			}
			if i < len(data) && data[i] == '\n' {
				out = append(out, '\n')
			}
			continue
		}

		out = append(out, ch)
	}

	return out
}
